#!/bin/bash

podman run \
    --name dev \
    -d -ti \
    -v ~/.gitconfig:/home/developer/.gitconfig \
    -v .ssh:/home/developer/.ssh:U \
    my-development-environment:latest \
    zsh

podman exec -ti dev zsh
