#!/bin/bash

podman run \
    --name dev \
    -d -ti \
    --volume ~/.gitconfig:/home/developer/.gitconfig \
    --volume .ssh:/home/developer/.ssh:U \
    --hostname devcontainer \
    my-development-environment:latest \
    zsh

podman exec -ti dev zsh
