#!/bin/bash

podman run \
    --name devcontainer \
    -d -ti \
    --volume ~/.gitconfig:/home/developer/.gitconfig:U \
    --volume .ssh:/home/developer/.ssh:U \
    --hostname devcontainer \
    my-development-environment:latest \
    zsh

podman exec -ti devcontainer zsh
