#!/bin/bash

docker run --name devcontainer -d -ti --hostname devcontainer my-development-environment:latest zsh

    # --volume ~/.gitconfig:/home/developer/.gitconfig:U \
    # --volume .ssh:/home/developer/.ssh:U \

docker exec -ti devcontainer zsh
