theme = "mytheme" 

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]