theme = "mytheme" 

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
