require("core.base")
require("core.lazy")
require("core.color-scheme")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.indent-blankline")
require("plugins.nvim-treesitter")
require("plugins.comment")
require("plugins.telescope")
require("plugins.toggleterm")
require("core.original")
require("core.mappings")

